controller:
  image: "jenkins/jenkins"   # official image repo
  tag: "lts-jdk17"           # latest LTS; leave blank later if you want weekly
  imagePullPolicy: "IfNotPresent"

  numExecutors: 0

  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer

  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

  # ────── startupProbe tuned for very first boot ──────
  startupProbe:
    httpGet:
      path: /login
      port: http
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 120    # 20 min (was 10 min)

  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - github
    - docker-workflow
    - job-dsl

  serviceAccount:
    name: jenkins-sa
    create: false

  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      jenkins-config: |
        jenkins:
          systemMessage: "Jenkins"
          clouds:
            - kubernetes:
                name: "k8s"
                serverUrl: "https://kubernetes.default.svc"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                containerCapStr: "10"
                templates: []
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      id: "github-token"
                      username: "gh"
                      password: "changeme"
                      description: "GitHub PAT"
        jobs:
          - script: >
              pipelineJob('lesson-8-9') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote { url('https://github.com/AntonChubarov/goit-microservice-project.git') }
                        branches('lesson-8-9')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
                triggers { scm('H/5 * * * *') }
              }
