controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts-jdk17
    pullPolicy: IfNotPresent

  # Jenkins controller runs builds on K8s agents; keep 0 executors here
  numExecutors: 0

  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer

  # Right-size resources
  resources:
    requests:
      cpu: "300m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  # Init container resources template used by chart
  initContainerResources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  # Smaller heap
  javaOpts: >-
    -Djenkins.install.runSetupWizard=false
    -Xms256m -Xmx1024m
    -XX:+UseG1GC -XX:MaxMetaspaceSize=256m

  # Give first boot time for plugin install + JCasC
  startupProbe:
    httpGet: { path: /login, port: http }
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 180
  readinessProbe:
    httpGet: { path: /login, port: http }
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 180
  livenessProbe:
    httpGet: { path: /login, port: http }
    initialDelaySeconds: 240
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 90

  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi

  # IMPORTANT: force fresh, compatible plugins on every boot
  overwritePlugins: true
  installLatestPlugins: true

  # Nuke any stale .jpi from the PVC before Jenkins starts
  initContainers:
    - name: wipe-plugins
      image: busybox:1.36
      command: ['sh','-c','rm -rf /var/jenkins_home/plugins/* || true']
      volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home

  # Keep plugin set lean for faster stabilization
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - kubernetes-credentials-provider

  serviceAccount:
    name: jenkins-sa
    create: false

  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      jenkins-config: |
        jenkins:
          systemMessage: "Jenkins"
          clouds:
            - kubernetes:
                name: "k8s"
                serverUrl: "https://kubernetes.default.svc"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                containerCapStr: "10"
                templates: []
        jobs:
          - script: >
              pipelineJob('lesson-8-9') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote { url('https://github.com/AntonChubarov/goit-microservice-project.git') }
                        branches('lesson-8-9')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
                triggers { scm('H/5 * * * *') }
              }
