controller:
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - docker-workflow:latest
    - job-dsl:latest
    - pipeline-utility-steps:latest

  serviceAccount:
    name: jenkins-sa
    create: false

  # Auto-run the seed job once Jenkins is up
  initScripts:
    01-run-seed.groovy: |
      import jenkins.model.Jenkins
      import hudson.model.*
      def j = Jenkins.instance
      def seed = j.getItem('seed-job')
      if (seed != null) {
        println "[init] Scheduling initial build of 'seed-job'..."
        seed.scheduleBuild2(0)
      } else {
        println "[init] 'seed-job' not found at init time."
      }

  JCasC:
    configScripts:
      # Credentials for GitHub (used by seed job / pipeline)
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github-token
                      username: ${github_user}
                      password: ${github_pat}
                      description: GitHub PAT

      # Allow Job DSL without manual script approval
      jobdsl-security: |
        unclassified:
          job-dsl:
            useScriptSecurity: false

      # Seed job that creates the pipeline that builds/pushes and bumps the chart
      seed-job: |
        jobs:
          - script: >
              job('seed-job') {
                description('Job to generate pipeline for Django project')
                scm {
                  git {
                    remote {
                      url('https://github.com/AntonChubarov/goit-microservice-project.git')
                      credentials('github-token')
                    }
                    branches('*/lesson-8-9')
                  }
                }
                triggers {
                  scm('H/5 * * * *')
                }
                steps {
                  dsl {
                    text('''
                      pipelineJob("goit-django-docker") {
                        definition {
                          cpsScm {
                            scm {
                              git {
                                remote {
                                  url("https://github.com/AntonChubarov/goit-microservice-project.git")
                                  credentials("github-token")
                                }
                                branches("*/lesson-8-9")
                              }
                            }
                            scriptPath("lesson-8-9/Jenkinsfile")
                          }
                        }
                      }
                    ''')
                    ignoreExisting(false)
                    removedJobAction('DELETE')
                    useScriptSecurity(false)
                  }
                }
              }
