controller:
  # ───────────── Docker image ─────────────
  image:
    registry: ""                 # empty → docker.io (default)
    repository: "jenkins/jenkins"
    tag: "2.466.1-lts-jdk17"     # << moved here
    pullPolicy: IfNotPresent

  numExecutors: 0                # defined only once

  # Admin user
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer

  # Controller resources
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

  # Startup probe — give Jenkins up to 10 min to boot
  startupProbe:
    httpGet:
      path: /login
      port: http
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 60   # 60 × 10 s = 10 min

  # Persistence
  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi

  # Plugin list
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - github
    - docker-workflow
    - job-dsl

  # Use existing SA created elsewhere
  serviceAccount:
    name: jenkins-sa
    create: false

  # ───────────── Jenkins Configuration-as-Code ─────────────
  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      jenkins-config: |
        jenkins:
          systemMessage: "Jenkins"
          clouds:
            - kubernetes:
                name: "k8s"
                serverUrl: "https://kubernetes.default.svc"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                containerCapStr: "10"
                templates: []
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      id: "github-token"
                      username: "gh"
                      password: "changeme"
                      description: "GitHub PAT"
        jobs:
          - script: >
              pipelineJob('lesson-8-9') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote { url('https://github.com/AntonChubarov/goit-microservice-project.git') }
                        branches('lesson-8-9')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
                triggers { scm('H/5 * * * *') }
              }
