controller:
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer

  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - github
    - docker-workflow
    - job-dsl

  serviceAccount:
    name: jenkins-sa
    create: false
