controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts-jdk17
    pullPolicy: IfNotPresent

  numExecutors: 0

  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer

  # Give Jenkins more room and a predictable heap
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  # Skip setup wizard + set sane heap/GC so boot doesn't thrash
  javaOpts: "-Djenkins.install.runSetupWizard=false -Xms512m -Xmx2048m -XX:+UseG1GC -XX:MaxMetaspaceSize=512m"

  # ────── startupProbe tuned for first boot ──────
  startupProbe:
    httpGet:
      path: /login
      port: http
    initialDelaySeconds: 60     # give WAR unpack/JCasC a head start
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 180       # ~30 minutes max; usually ready in 3–8 min

  # Keep your PVC (verify the storage class exists)
  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 10Gi

  # Keep your plugins (note: first boot downloads can be slow)
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - github
    - docker-workflow
    - job-dsl

  serviceAccount:
    name: jenkins-sa
    create: false

  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      jenkins-config: |
        jenkins:
          systemMessage: "Jenkins"
          clouds:
            - kubernetes:
                name: "k8s"
                serverUrl: "https://kubernetes.default.svc"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                containerCapStr: "10"
                templates: []
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      id: "github-token"
                      username: "gh"
                      password: "changeme"
                      description: "GitHub PAT"
        jobs:
          - script: >
              pipelineJob('lesson-8-9') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote { url('https://github.com/AntonChubarov/goit-microservice-project.git') }
                        branches('lesson-8-9')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
                triggers { scm('H/5 * * * *') }
              }
