apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.revision }}
    path: lesson-8-9/charts/django-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
