applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/AntonChubarov/goit-microservice-project.git
      # All deployable content is inside the lesson-db-module folder in the repo:
      path: lesson-db-module/charts/django-app
      targetRevision: lesson-db-module
      helm:
        valueFiles:
          - values.yaml
        values: |
          config:
            POSTGRES_HOST: "${rds_host}"
            POSTGRES_USER: "${rds_username}"
            POSTGRES_NAME: "${rds_db_name}"
            POSTGRES_PASSWORD: "${rds_password}"
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: ${github_repo_url}
    username: ${github_user}
    password: ${github_pat}

repoConfig:
  insecure: "true"
  enableLfs: "true"
