applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/AntonChubarov/goit-microservice-project.git
      # All deployable content is inside the lesson-db-module folder in the repo:
      path: lesson-db-module/charts/django-app
      targetRevision: lesson-db-module
      helm:
        valueFiles:
          - values.yaml
        values: |
          # Disable bundled PostgreSQL; we point to RDS instead.
          postgresql:
            enabled: false

          # App config -> becomes a ConfigMap and then env via envFrom.
          config:
            POSTGRES_HOST: "${rds_host}"
            POSTGRES_PORT: "5432"
            POSTGRES_USER: "${rds_username}"
            POSTGRES_NAME: "${rds_db_name}"
            POSTGRES_PASSWORD: "${rds_password}"
            # Provide both, since your logs look for POSTGRES_URL and many libs use DATABASE_URL.
            POSTGRES_URL: "postgres://${rds_username}:${rds_password}@${rds_host}:5432/${rds_db_name}"
            DATABASE_URL: "postgres://${rds_username}:${rds_password}@${rds_host}:5432/${rds_db_name}"

    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: ${github_repo_url}
    username: ${github_user}
    password: ${github_pat}

repoConfig:
  insecure: "true"
  enableLfs: "true"
