image:
  repository: 458845291257.dkr.ecr.eu-central-1.amazonaws.com/lesson-8-9-ecr
  tag: latest
  pullPolicy: IfNotPresent
#  pullPolicy: Always
service:
  type: LoadBalancer
  port: 8000
ingress:
  enabled: false
