replicaCount: 2

image:
  repository: ""
  tag: "latest"

containerPort: 8000
readinessPath: /db-check
livenessPath: /db-check

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80

env:
  DJANGO_SETTINGS_MODULE: "test_project.settings"
  SECRET_KEY: "change_me"
  DEBUG: "True"
  ALLOWED_HOSTS: "*"

secrets: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
