apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: django-app
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: django-app
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
