installCRDs: true

global:
  image:
    tag: ""

server:
  insecure: true
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
  extraArgs:
    - --insecure

configs:
  params:
    server.insecure: true

applicationSet:
  enabled: true

controller:
  replicas: 1

repoServer:
  replicas: 1

dex:
  enabled: false
